name: p4env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - psi4
  - conda-forge/label/libint_dev::libint
  
  - pytest-xdist
  - dftd3-python
  - dftd4-python
  - toml
  - gcp-correction
